In [11]:
import numpy as np
import gtda

In [58]:
class Space:
    """
    Create a space object with a name and an embedding dimension
    """
    def __init__(self, name, edim):
        self.name = name
        self.edim = edim

    def sample(self, n):
        raise NotImplementedError()

    def poincare_polynomial(self):
        raise NotImplementedError()

    def barcode(self):
        raise NotImplementedError()

In [59]:
class Sphere(Space):
    def __init__(self, dim):
        """
        Create a sphere of dimension dim.  This is the set of unit vectors 
        in R ^(dim + 1), so the embedding dimension is dim+1.
        """
        self.dim = dim
        super().__init__('S^{' + str(dim) + '}', dim+1)

    def sample(self, n):
        """
        Returns a numpy matrix of shape n x edim, where each row is a
        random point on the sphere.  To do this, we generate a matrix
        of shape n x edim of standard normal random variables, and then
        normalize each row to have unit length.
        """
        x = np.random.randn(n, self.edim)
        x /= np.linalg.norm(x, axis=1)[:, None]
        return x

    def poincare_polynomial(self):
        """
        This returns the correct answer for the Poincare polynomial 
        of the sphere, represented as an integer-valued numpy array.
        The i-th entry is the coefficient of t^i, which is the rank
        of the i-th homology group.  In the case of the sphere, the
        Poincare polynomial is 1 + t^dim.
        """
        p = np.zeros(self.dim+1, dtype=int)
        p[0] = 1
        p[self.dim] = 1
        return p


In [62]:
class ComplexProjectiveSpace(Space):
    def __init__(self, cdim):
        self.cdim = cdim
        super().__init__('CP^{' + str(cdim) + '}', (cdim+1) ** 2)

    def sample(self, n):
        d = self.cdim+1
        x = np.random.randn(n, d) + 1j * np.random.randn(n, d)
        x /= np.linalg.norm(x, axis=1)[:, None]
        return x.reshape(n,d,1) * np.conj(x.reshape(n, 1, d))

    def poincare_polynomial(self):
        d = self.cdim
        p = np.zeros(2*d + 2, dtype=int)
        p[0::2] = 1
        return p

In [61]:
X = Sphere(4)
print(X.name)
print(X.dim)
print(X.edim)

S^{4}
4
5


In [68]:
X = ComplexProjectiveSpace(3)
X.name

'CP^{3}'

In [70]:
X.cdim

3

In [71]:
x = X.sample(2)

In [72]:
x

array([[[ 0.13980208+0.j        ,  0.01481653-0.21553376j,
         -0.08568676+0.10532462j,  0.22377766-0.07121231j],
        [ 0.01481653+0.21553376j,  0.33386005+0.j        ,
         -0.1714609 -0.12094129j,  0.13350491+0.3374522j ],
        [-0.08568676-0.10532462j, -0.1714609 +0.12094129j,
          0.13186853+0.j        , -0.19080683-0.12494337j],
        [ 0.22377766+0.07121231j,  0.13350491-0.3374522j ,
         -0.19080683+0.12494337j,  0.39446933+0.j        ]],

       [[ 0.82217591+0.j        ,  0.2144913 -0.23409549j,
         -0.17393809-0.08990943j,  0.08361008+0.00816465j],
        [ 0.2144913 +0.23409549j,  0.12261027+0.j        ,
         -0.01977778-0.07298063j,  0.01948771+0.02593604j],
        [-0.17393809+0.08990943j, -0.01977778+0.07298063j,
          0.04663013+0.j        , -0.01858125+0.00741592j],
        [ 0.08361008-0.00816465j,  0.01948771-0.02593604j,
         -0.01858125-0.00741592j,  0.00858369+0.j        ]]])

In [56]:
np.linalg.norm(x[0] @ x[0] - x[0])

3.813551952255812e-16

In [47]:
d = 2
n = 1
x = np.random.randn(n, d) + 1j * np.random.randn(n, d)
x /= np.linalg.norm(x, axis=1)[:, None]
y = x.reshape(n,d,1) * np.conj(x.reshape(n, 1, d))


In [36]:
x

array([[ 0.33683511+0.15294102j, -0.68767288-0.62470566j]])

In [43]:
x1 = np.conj(x.reshape(n, 1, d))
x1

array([[[ 0.33683511-0.15294102j, -0.68767288+0.62470566j]]])

In [46]:
x1 * x.reshape(n,d,1)

array([[[ 0.13684885+0.j        , -0.32717549+0.10524941j],
        [-0.32717549-0.10524941j,  0.86315115+0.j        ]]])

In [65]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [67]:
a.reshape(3,1,2)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])